name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  release-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: InstallDeps
        run: sudo apt-get update && sudo apt-get install -y libboost-all-dev libgraphviz-dev
      
      - name: Configure CMake
        run: cmake --preset release
      
      - name: Build
        run: |
            cmake --build --preset release --target pivot_exec -j
            tar vczf ${{github.workspace}}/build/pivot-linux-x86_64.tar.gz -C ${{github.workspace}}/build pivot libpivot.a

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{github.workspace}}/build/pivot-linux-x86_64.tar.gz

  release-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: InstallDeps
        run: brew install bison boost

      - name: InstallGraphviz
        run: |
          git clone --depth 1 -b 12.2.0 https://gitlab.com/graphviz/graphviz.git
          cmake -S ${{github.workspace}}/graphviz -B ${{github.workspace}}/graphviz/build \
            -DCMAKE_BUILD_TYPE=Release \
            -DBISON_EXECUTABLE=$(brew --prefix bison)/bin/bison \
            -DCMAKE_INSTALL_PREFIX=~/.local
          cmake --build ${{github.workspace}}/graphviz/build --target install -j

      - name: Configure CMake
        run: cmake --preset release -DGRAPHVIZ_INCLUDE_PATH=~/.local/include/graphviz

      - name: Build
        run: |
            cmake --build --preset release --target pivot_exec -j
            tar vczf ${{github.workspace}}/build/pivot-macos.tar.gz -C ${{github.workspace}}/build pivot libpivot.a

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{github.workspace}}/build/pivot-macos.tar.gz
