name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  release-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure CMake
        env:
          VCPKG_ROOT: /usr/local/share/vcpkg
        run: cmake --preset release
      
      - name: Build
        run: |
            cmake --build --preset release --target pivot_exec -j
            tar vczf ${{github.workspace}}/build/pivot-linux-x86_64.tar.gz -C ${{github.workspace}}/build pivot libpivot.a

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{github.workspace}}/build/pivot-linux-x86_64.tar.gz

  release-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: InstallDeps
        run: |
          brew install vcpkg
          git clone --depth 1 https://github.com/microsoft/vcpkg "$HOME/vcpkg"

      - name: Configure CMake
        env:
          VCPKG_ROOT: /Users/runner/vcpkg
        run: |
          cmake --preset release

      - name: Build
        run: |
            cmake --build --preset release --target pivot_exec -j
            tar vczf ${{github.workspace}}/build/pivot-macos.tar.gz -C ${{github.workspace}}/build pivot libpivot.a

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{github.workspace}}/build/pivot-macos.tar.gz
