name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  debug:
    runs-on: ubuntu-22.04

    env:
      BUILD_TYPE: Debug
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v4

    - name: CheckFormat
      run: ${{github.workspace}}/tools/git/pre-commit

    - name: InstallDeps
      run: sudo apt-get update && sudo apt-get install -y cppcheck libboost-all-dev libgraphviz-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE

    - name: Lint
      run: ${{github.workspace}}/tools/lint.sh

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target test_pivot -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
  release:
    runs-on: ubuntu-22.04

    env:
      BUILD_TYPE: Release
      CC: gcc
      CXX: g++

    steps:
      - uses: actions/checkout@v4

      - name: InstallDeps
        run: sudo apt-get update && sudo apt-get install -y libboost-all-dev libgraphviz-dev valgrind

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target test_pivot -j
      
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all --error-exitcode=1 ./tests/test_pivot
