name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  debug-test:
    runs-on: ubuntu-22.04

    env:
      CC: clang-13
      CXX: clang++-13

    steps:
    - uses: actions/checkout@v4

    - name: CheckFormat
      run: ${{github.workspace}}/tools/git/pre-commit

    - name: InstallDeps
      run: sudo apt-get update && sudo apt-get install -y cppcheck libboost-all-dev libgraphviz-dev

    - name: Configure CMake
      run: cmake --preset test

    - name: Lint
      run: ${{github.workspace}}/tools/lint.sh

    - name: Build
      run: cmake --build --preset test -j

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build --output-on-failure

  release-build:
    runs-on: ubuntu-22.04

    env:
      CC: gcc
      CXX: g++

    steps:
      - uses: actions/checkout@v4

      - name: InstallDeps
        run: sudo apt-get update && sudo apt-get install -y libboost-all-dev libgraphviz-dev valgrind

      - name: Configure CMake
        run: cmake --preset release
      
      - name: Build
        run: cmake --build --preset release --target test_pivot -j

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test_pivot
          path: ${{github.workspace}}/build/tests/test_pivot

  release-test:
    runs-on: ubuntu-22.04

    needs: release-build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test_pivot

      - name: InstallDeps
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Test
        run: |
            chmod +x ./test_pivot
            valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all --error-exitcode=1 ./test_pivot

  mac-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: InstallDeps
        run: brew install bison boost

      - name: InstallGraphviz
        run: |
            git clone https://gitlab.com/graphviz/graphviz.git
            cmake -S ${{github.workspace}}/graphviz -B ${{github.workspace}}/graphviz/build \
              -DCMAKE_BUILD_TYPE=Release \
              -DBISON_EXECUTABLE=$(brew --prefix bison)/bin/bison \
              -DCMAKE_INSTALL_PREFIX=~/.local
            cmake --build ${{github.workspace}}/graphviz/build --target install -j

      - name: Configure CMake
        run: cmake --preset release -DGRAPHVIZ_INCLUDE_PATH=~/.local/include/graphviz

      - name: Build
        run: cmake --build --preset release --target test_pivot -j

      - name: Test
        run: ctest --test-dir ${{github.workspace}}/build --output-on-failure
